### ISSUE TITLE
NetworkOperationsHandlerImpl.java line 230 Crash

### ISSUE THREAD

**Issue by CWftw** [kinecosystem/kin-android#16]
Using 'org.kin.sdk.android:base-compat:0.4.1'

We have seen thousands of these crashes over the past 30 days, nearly 1000 of them on December 26 when the servers were particularly unstable. Please let me know if this has been fixed in a newer version, although we have been stuck at 0.4.1 because of #15.

`Fatal Exception: org.kin.sdk.base.tools.NetworkOperationsHandlerException$OperationTimeoutException: Op timed out
       at org.kin.sdk.base.tools.NetworkOperationsHandlerImpl.expire(NetworkOperationsHandlerImpl.java:230)
       at org.kin.sdk.base.tools.NetworkOperationsHandlerImpl.access$handleError(NetworkOperationsHandlerImpl.java:205)
       at org.kin.sdk.base.tools.NetworkOperationsHandlerImpl$queueOperation$$inlined$apply$lambda$1.run(NetworkOperationsHandlerImpl.java:220)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)`

**Comment by chaseeb** [comment]
These were issues with the Solana network, and have since been resolved.
