### ISSUE TITLE
Balance.value(int) error - (compatibility mode)

### ISSUE THREAD

**Issue by showered** [kinecosystem/kin-android#7]
I think this is probably a low priority bug as I was probably doing it the wrong way in the first place.

But nevertheless, an error did occur that didn't occur previously, so I'll raise a ticket.

I was previously converting `Balance` object to a String by using the following code:

```
balance.value(0)
```

However, this resulted in an error after swapping to the `base-compat` SDK.

```
java.lang.ArithmeticException: Rounding necessary
    at java.math.BigDecimal.roundingBehavior(BigDecimal.java:2818)
    at java.math.BigDecimal.dividePrimitiveLongs(BigDecimal.java:1127)
    at java.math.BigDecimal.setScale(BigDecimal.java:1897)
    at java.math.BigDecimal.setScale(BigDecimal.java:1945)
    at org.kin.sdk.base.models.KinAmount.toString(KinAmount.kt:35)
    at kin.sdk.internal.BalanceImpl.value(BalanceImpl.kt:9)
    at io.peerbet.peerbet.KinWalletModule.getKinBalance(KinWalletModule.java:171)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:888)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
    at android.os.Looper.loop(Looper.java:213)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
    at java.lang.Thread.run(Thread.java:929)
```

I was able to fix it by changing my code to:

```
balance.value().toPlainString()
```

**Comment by showered** [comment]
Below is the `Balance` interface. It's the "precision" option that is failing for me.

https://kinecosystem.github.io/kin-android/docs/kin.sdk/-balance/

| Name | Summary |
|---|---|
| [value](value.md) | `abstract fun value(): `[`BigDecimal`](https://docs.oracle.com/javase/6/docs/api/java/math/BigDecimal.html)<br>`abstract fun value(precision: `[`Int`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-int/index.html)`): `[`String`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html) |

**Comment by kikengineering** [comment]
Classic rounding issue. Thanks @showered 
0.1.7 has been released to address this issue.
